theme: jekyll-theme-minimal
title: MUSCARI
description: Multi-task Spectral Clustering AlgoRIthm
logo: http://pages.discovery.wisc.edu/~jshin/multi-species-proteome/muscari_cartoon.png
show_downloads: true
